version: "2"
services:
  web:
    build: .
    links:
      - neo4j
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=/app/main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=8080'
    command: flask run --host=0.0.0.0 --port=8080

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "none"
